"use client";
import React, { useRef } from "react";
import Head from "next/head";
import Header from "./containers/Header";
import Banner from "./containers/Banner";
import OneBanner from "./containers/OneBanner";
import TwoBanner from "./containers/TwoBanner";
import NextLevel from "./containers/NexeLevel";
import Marqee from "./containers/Marqee";
import Footer from "./containers/Footer";
import Image from "next/image";
import Smile from "../public/smile.svg";
import dynamic from "next/dynamic";

const AnimatedCursor = dynamic(() => import("react-animated-cursor"), {
  ssr: false,
});

const MARQEE_TEXT = `PPC advertising. CRO. Web analytics . CRM . Landing page optimization.
A/B testing. Marketing automation.`;
const LOOKING_FOR = `If you're looking for a`;

export default function Home() {
  const oneBannerRef = useRef(null);
  const twoBannerRef = useRef(null);

  const handleScrollToOneBanner = () => {
    oneBannerRef?.current?.scrollIntoView({ behavior: "smooth" });
  };
  const handleScrollToTwoBanner = () => {
    twoBannerRef?.current?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <AnimatedCursor
        innerSize={6}
        outerSize={40}
        innerScale={1}
        outerScale={1}
        outerAlpha={0}
        hasBlendMode={true}
        innerStyle={{
          backgroundColor: "#000",
        }}
        outerStyle={{
          border: "2px solid #000",
        }}
      />
      <Head>
        <title>Waheed Iqbal Portfolio</title>
        <meta
          name="description"
          content="Generated by Waheed Iqbal Portfolio"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={``}>
        <Header
          scrollToOneBanner={handleScrollToOneBanner}
          scrollToTwoBanner={handleScrollToTwoBanner}
        />
        <Banner />
        <OneBanner ref={oneBannerRef} />
        <TwoBanner ref={twoBannerRef} />
        <Marqee top={true} direction="left">
          {MARQEE_TEXT}
        </Marqee>
        <Marqee top={false} direction="right">
          {MARQEE_TEXT}
        </Marqee>
        <div className="lookingFor">
          {LOOKING_FOR}
          <Image src={Smile} alt="Waheed Iqbal" width={200} height={200} />
        </div>
        <NextLevel />
        <Footer />
      </main>
    </>
  );
}
